### ISSUE TITLE
Measure thread pools

### ISSUE THREAD

**Issue by chemicL** [allegro/envoy-control#138]
In our internal flavour we monitor the state of thread pools utilisation, queues, etc. It would be a great benefit for this functionality to be available in the OSS version of e-c. If there's interest I'll be happy to share specs and how we do it.

**Comment by pzmi** [comment]
We could also use [Micrometer's thread pool monitoring](https://micrometer.io/docs/ref/jvm)

**Comment by gut9** [comment]
I'll work on this
