### ISSUE TITLE
Are  there any examples to show dynamic Listeners

### ISSUE THREAD

**Issue by carolove** [allegro/envoy-control#228]
hi, all
     are there any examples to show how to use dynamic Listeners?
it is Very grateful.

**Comment by slonka** [comment]
Hi @carolove - here is our factory class that generates listeners and other dependent resources: https://github.com/allegro/envoy-control/blob/master/envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/EnvoyListenersFactory.kt#L50 do you have anything in particular in mind?

**Comment by carolove** [comment]
thank you for your reply, i hnow this listener generates code, i want a example just like  quickstart(https://envoy-control.readthedocs.io/en/latest/quickstart/)

**Comment by slonka** [comment]
Here is an example config using dynamic listeners: https://github.com/allegro/envoy-control/blob/master/envoy-control-tests/src/main/resources/envoy/config_ads.yaml#L24-L27 . If you would describe the problem you're trying to solve and describe the context in which you need to configure listeners dynamically it would be easier for me to understand.

**Comment by carolove** [comment]
thank you, i understand
