### ISSUE TITLE
Migrate deprecated options from envoy v.1.12.0

### ISSUE THREAD

**Issue by wookieJ** [allegro/envoy-control#38]
Following options are marked as deprecated in envoy v.1.12.0: https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated#version-1-12-0-october-31-2019. Update them to keep them up to date.

**Comment by MarcinFalkowski** [comment]
Even before v1.12.0 we already used some deprecated feautures.

We can check metric `runtime.deprecated_feature_use` to monitor how many deprecated options we use.

**Comment by MarcinFalkowski** [comment]
Done in #85
